version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    expose:
      - 3306
    volumes:
      - persistent:/var/lib/mysql
    labels:
      kompose.service.type: clusterip

  adminer:
    image: adminer
    restart: always
    expose:
      - 8080
    labels:
      kompose.service.type: clusterip
volumes:
  persistent:
